from api.health.views import (
    DailyLogListCreateView, 
    DailyLogDetailView, 
    SymptomListView, 
    SymptomDetailView, 
    SymptomEntryListCreateView, 
    SymptomEntryDetailView, 
    TimelineView,
    EpisodeListCreateView,
    EpisodeActiveView,
    EpisodeHistoryView,
    EpisodeDetailView,
    EpisodeCloseView,
    MedicationListCreateView,
    MedicationDetailView,
    ChronicConditionListCreateView,
    ChronicConditionDetailView,
    MedicationLogListCreateView,
    MedicationLogDetailView,
    SymptomAnalyticsView,
    DailyTrendsView,
    MedicationEffectView,
    MedicationAdherenceView
    )
from django.urls import path

urlpatterns = [
    path('logs/', DailyLogListCreateView.as_view(), name='daily-log-list-create'),
    path('logs/<int:pk>/', DailyLogDetailView.as_view(), name='daily-log-detail'),
    path('symptoms/', SymptomListView.as_view(), name='symptom-list'),
    path('symptoms/<int:pk>/', SymptomDetailView.as_view(), name='symptom-detail'),
    path('symptom-entries/', SymptomEntryListCreateView.as_view(), name='symptom-entry-list'),
    path('symptom-entries/<int:pk>/', SymptomEntryDetailView.as_view(), name='symptom-entry-detail'),
    path('timeline/', TimelineView.as_view(), name='timeline'),
    path('episodes/', EpisodeListCreateView.as_view(), name='episode-list-create'),
    path('episodes/active/', EpisodeActiveView.as_view(), name='episode-active'),
    path('episodes/history/', EpisodeHistoryView.as_view(), name='episode-history'),
    path('episodes/<int:pk>/', EpisodeDetailView.as_view(), name='episode-detail'),
    path('episodes/<int:pk>/close/', EpisodeCloseView.as_view(), name='episode-close'),
    path('medications/', MedicationListCreateView.as_view(), name='medication-list'),
    path('medications/<int:pk>/', MedicationDetailView.as_view(), name='medication-detail'),
    path('chronic-conditions/', ChronicConditionListCreateView.as_view(), name='chronic-condition-list'),
    path('chronic-conditions/<int:pk>/', ChronicConditionDetailView.as_view(), name='chronic-condition-detail'),
    path('medication-logs/', MedicationLogListCreateView.as_view(), name='medication-log-list'),
    path('medication-logs/<int:pk>/', MedicationLogDetailView.as_view(), name='medication-log-detail'),
    path('analytics/symptoms/', SymptomAnalyticsView.as_view()),
    path('analytics/daily-trends/', DailyTrendsView.as_view()),
    path('analytics/medication-effect/', MedicationEffectView.as_view()),
    path('analytics/medication-adherence/', MedicationAdherenceView.as_view()),
]